### ISSUE TITLE
Create VMs not depending on template in the target datacenter

### ISSUE THREAD

**Issue by pibong** [imjoey/terraform-provider-ovirt#122]
Hi,
thanks for your great job here, I really appreciate your effort.

If I am not wrong, now provider chooses by default thin Storage Allocation, so each VM is dependent on the template which must be present in the datacenter. I have multiple datacenters and for some business reasons VMs can be moved out to other DCs, therefore I usually use the clone option in order to make VMs independent from template.

Just for better understanding, in the POST request for creating a VM from a template with "thin storage allocation", post data looks like this:
```
<vm>
    ...
    <original_template href="/ovirt-engine/api/templates/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"/>
    <template href="/ovirt-engine/api/templates/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"/>
</vm>
```

while in "clone storage allocation":
```
<vm>
    ...
    <original_template href="/ovirt-engine/api/templates/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"/>
    <template href="/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000" id="00000000-0000-0000-0000-000000000000"/>
</vm>
```

Do you think it could be implemented?

Thanks
Pietro

**Comment by imjoey** [comment]
hi @pibong, sorry for my late reply. Very glad to see that this project is in your practical use. Sure, this is a common requirement and it will be supported in the next release. Thanks a lot. 😄

**Comment by stfnbrndg** [comment]
Came here looking for this. We also have business reasons for having multiple Data Centers. It's not practical to migrate templates alongside the VMs.

Thanks for your hard work imjoey, this is a very useful project for us.

**Comment by imjoey** [comment]
Hi @pibong @stfnbrndg, Sorry for still not having fixed it. I will try my best to have this implemented as soon as possible. Thank you all for reporting.

**Comment by imjoey** [comment]
Hi @pibong @stfnbrndg . The `clone` option has been added to support creating a VM from template independently. It has been merged in the new `v0.2.1` release. Please update the provider for this functionality. Please reopen this issue if any issues. Thanks.

**Comment by stfnbrndg** [comment]
Thank you for fixing this! I'm grateful for the work you put into this. I hope I didn't place pressure on you - I just find what your project very useful.

I'm looking forward to trying it out.

**Comment by imjoey** [comment]
@stfnbrndg thanks for your kindness. I'm obligated to keep maintaining this project to build better ecosystem for oVirt. Also good to see it's useful for you and that's my great pleasure. Reopen this if any error occurs.
