### ISSUE TITLE
Use count to deploy multiple vms from one terraform file

### ISSUE THREAD

**Issue by sjoshi10** [imjoey/terraform-provider-ovirt#127]
Hi @imjoey , 

Currently, there is no functionality to allow deployment of multiple VMs from 1 terraform file. I have been creating new file for each VMs. It would be useful to have this functionality for deploying cluster of VMs. In aws_instance resource for aws provider, it allows us to use count to deploy multiple vms fo the same kind. I have used this to deploy cluster on AWS. It would be awesome to have this functionality for OVirt too.

**Comment by stfnbrndg** [comment]
Hi @sjoshi10, 

This functionality actually does exist for this provider / project.

You can either list multiple resources in your Terraform file, or you can use count as you mentioned in your initial comment.

**Comment by sjoshi10** [comment]
@stfnbrndg I understand we can list mulitple resource in one terraform file but I have not been able to get count to work. Have you gotten it working? If so, can you give me an example.

**Comment by sjoshi10** [comment]
@stfnbrndg Nervermind. I see why it wasn't working before. Thanks for pointing it out! Appreciate it!

**Comment by imjoey** [comment]
Thanks @stfnbrndg for your help. @sjoshi10 if you still have any issue, please let me know.
