### ISSUE TITLE
Error using Terraform 0.12.0-beta2

### ISSUE THREAD

**Issue by llomgui** [imjoey/terraform-provider-ovirt#128]
Hi,

I tried to use this provider with Terraform 0.12.0-beta2.
I built it this way:
```
$ mkdir -p $GOPATH/src/github.com/imjoey
$ cd $GOPATH/src/github.com/imjoey
$ git clone git@github.com:imjoey/terraform-provider-ovirt
$ cd $GOPATH/src/github.com/imjoey/terraform-provider-ovirt
$ go get github.com/hashicorp/terraform@v0.12.0-beta2
$ go build
```

I'm getting this error: 
```
Error: rpc error: code = Unavailable desc = transport is closing
panic: can't convert map[string]string{} to cty.Value
```

Can you help me?

**Comment by imjoey** [comment]
Hi @llomgui , thanks for reporting this. For now this provider has not yet been compatible with Terraform `v0.12`. After referring to the [official upgrade guides](https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers), I probably need some time to fix the v0.12-compatible issues gradually along with the upcoming final release of v0.12. Honestly, I'm busy with daily work, so if v0.12, which is also not production-ready, is not the must-be version for you, please take a try for 0.11.x. Thanks.

**Comment by llomgui** [comment]
Hi @imjoey,

I built it the wrong way I guess.

Solution to use the provider with v0.12.0-beta2:

```
$ mkdir -p $GOPATH/src/github.com/hashicorp
$ cd $GOPATH/src/github.com/hashicorp
$ git clone https://github.com/hashicorp/terraform.git
$ export GO111MODULE=on 
$ go get github.com/imjoey/terraform-provider-ovirt
$ cp $GOPATH/bin/terraform-provider-ovirt ~/.terraform.d/plugins
```

Then I tested with:

```
provider "ovirt" {
  username = var.ovirt_username
  url      = var.ovirt_url
  password = var.ovirt_pass
}

data "ovirt_clusters" "filtered_clusters" {
  name_regex = "^Default"
}

resource "ovirt_vm" "vm" {
  name        = "terraform_vm"
  cluster_id  = data.ovirt_clusters.filtered_clusters["clusters"].0.id
  memory      = 2048
  template_id = "c5ad9f9c-7b97-404a-b5e8-9a3702e94820"
}
```

**Comment by imjoey** [comment]
@llomgui Thanks for your feedback. Well the provider binary is needed to be installed in the user plugins directory. `terraform init` is also required beforehand. Good to see the problem got resolved. Close this issue now. Feel free to reopen if there are any v0.12-incompatiable problems. Thank you very much.
