### ISSUE TITLE
Add it to Terraform community providers list

### ISSUE THREAD

**Issue by mykaul** [imjoey/terraform-provider-ovirt#129]
Fill in https://docs.google.com/forms/d/e/1FAIpQLSeenG02tGEmz7pntIqMKlp5kY53f8AV5u88wJ_H1pJc2CmvKA/viewform#responses to get it into https://www.terraform.io/docs/providers/type/community-index.html

**Comment by imjoey** [comment]
Hi @mykaul , thanks for your help. This has already been added into that page, please see the last few lines. 😄

**Comment by mykaul** [comment]
Whoops.
