### ISSUE TITLE
Attribute memory does not seem to be set

### ISSUE THREAD

**Issue by yalinglee** [imjoey/terraform-provider-ovirt#59]
It seems that the attribute `memory` is not passed to the Ovirt API during the creation of the VM.

Here is my terraform code:
```
resource "ovirt_vm" "my_vm" {
  name      = "my_vm"
  cluster_id   = "${cluster_id}"
  template_id  = "${template_id}"
  cores     = 2
  memory = 4294967296
}
```

Here is the output: 
```
ovirt_vm.my_vm: Creating...
  cluster_id: "" => "3b1f3529-13bb-1420-0045-0000000002b1"
  cores:      "" => "2"
  memory   "" => "4294967296"
  name:       "" => "my_vm"
  sockets:    "" => "1"
  status:     "" => "<computed>"
  template_id:   "" => "my_tempate"
  threads:    "" => "1"
```
But after the VM is created, the memory value does not match the value specified in the template. Please let me know if I missed anything. Thanks!

**Comment by imjoey** [comment]
Sorry for this obvious mistake and it will get fixed soon. Thanks @yalinglee .

**Comment by imjoey** [comment]
@yalinglee  #60 fixed this issue. You could specify a integer in MB unit for the `memory` attribute.
