### ISSUE TITLE
Not setting "logical_name" in "ovirt_disk_attachment" will cause resource to be recreated

### ISSUE THREAD

**Issue by yalinglee** [imjoey/terraform-provider-ovirt#67]
I noticed that a recent change in the `ovirt_disk_attachment` resource might have some side effects. If the `ovirt_disk_attachment` resource is created without the`logical_name` attribute set (it's an optional value), it will be assigned a logical name `/dev/vda` by default during creation. If the user runs `terraform apply` again using the same code, Terraform will attempt to destroy the resource just created because it detects the change from `/dev/vda` to `''`. This is probably not the desired behavior. If we want to set `ForceNew` to true for `logical_name`, should it be a required field instead? Or should a default value be provided?

**Comment by imjoey** [comment]
Exactly, good catch, thanks. I would like to prefer changing `logical_name` attribute to be `required`, since it will be set with different default values for Linux or Windows.

**Comment by imjoey** [comment]
hi @yalinglee , a new related pr has got merged, which just removed the `logical_name` attribute. Please see #69 for details reason. Sorry for the inconvenience.
